### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by LuisEduLeiva** [fjaros/wowchat#74] opened 2022-04-20 20:46 UTC
hello, yesterday my bot stopped working, I don't know if it was something related to the wow server (which migrated to another server) or something related to Discord, but I can't run the wowchat bot since then, I tried it from my mac and from a vps in google cloud.

Im using 1.3.8 latest release

```
MacBook-Pro-de-Luis:wowchat baneside$ java -jar wowchat.jar wowchat.conf
16:38:18.037 [main] INFO wowchat.WoWChat$ - Running WoWChat - v1.3.8
16:38:19.988 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
16:38:20.032 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
16:38:20.034 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 16
16:38:20.041 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
16:38:20.056 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
16:38:20.064 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
16:38:20.075 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
16:38:20.081 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
16:38:20.085 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @28c71909
16:38:20.090 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
16:38:20.091 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
16:38:20.370 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 2147483648 bytes (maybe)
16:38:20.375 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/_x/q00_nhvx4_d9nrxxtsl3p9th0000gn/T (java.io.tmpdir)
16:38:20.376 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
16:38:20.384 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: MacOS
16:38:20.395 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
16:38:20.396 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
16:38:20.407 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
16:38:20.411 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
16:38:40.635 [main] INFO wowchat.WoWChat$ - Connecting to Discord...
16:38:42.520 [JDA RateLimit-Worker 1] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [6ff0af65aed32830-SCL]
16:38:43.985 [JDA RateLimit-Worker 2] DEBUG net.dv8tion.jda.internal.requests.Requester - Received response with following cf-rays: [6ff0af6dee9c2830-SCL]
16:38:44.033 [main] INFO net.dv8tion.jda.api.JDA - Login Successful!
16:38:44.192 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Creating new worker handle for shard pool 0
16:38:44.194 [main] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Running worker
16:38:44.198 [ConcurrentSessionController-Worker-0] DEBUG net.dv8tion.jda.api.utils.SessionControllerAdapter - Running connect node for shard Shard [0 / 1]
16:38:44.755 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
16:38:44.756 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Connected with gateway intents: 1100001011
16:38:44.757 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending Identify-packet...
16:38:44.950 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Got HELLO packet (OP 10). Initializing keep-alive.
16:38:45.241 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Setting incomplete count to 1
16:38:45.242 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Starting 75 second timeout for 1 guilds
16:38:46.073 [JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!
16:38:46.214 [JDA MainWS-ReadThread] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
16:38:46.360 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
16:38:46.362 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
16:38:46.426 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
16:38:46.427 [JDA MainWS-ReadThread] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
16:38:46.471 [JDA MainWS-ReadThread] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
16:38:46.542 [JDA MainWS-ReadThread] INFO wowchat.realm.RealmConnector - Connecting to realm server logon.stormforge.gg:3724
16:38:47.130 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 20313 (auto-detected)
16:38:47.146 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
16:38:47.154 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
16:38:47.196 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
16:38:47.198 [JDA MainWS-ReadThread] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
16:38:47.212 [JDA MainWS-ReadThread] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: f4:5c:89:ff:fe:95:71:3d (auto-detected)
16:38:47.306 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
16:38:47.307 [JDA MainWS-ReadThread] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
16:38:47.506 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
16:38:47.507 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
16:38:47.507 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
16:38:47.507 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
16:38:47.507 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
16:38:47.507 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
16:38:47.508 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
16:38:47.565 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
16:38:47.565 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
16:38:47.565 [JDA MainWS-ReadThread] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
16:38:47.617 [JDA MainWS-ReadThread] DEBUG net.dv8tion.jda.internal.handle.GuildSetupController - Finished setup for guild 812926112350863371 firing cached events 0
16:38:48.086 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
16:38:48.110 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
16:38:48.111 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
16:38:48.112 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
16:38:48.113 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
16:38:48.142 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
16:38:48.142 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
16:38:48.147 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@5ca5866a
16:38:48.282 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 05 04 08 EE 47 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 50 41 4E 44 49 43 48 41 54
16:38:48.729 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 5B 3F 54 F0 F8 5F B9 B0 DA 47 9B 37 8B 98 86 C5 68 5C D7 C8 2C 8C 02 5A 30 7A 5D 96 C4 3B 05 4F 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 E1 93 74 27 14 5A 7B 28 52 97 6E 0F F5 37 BA 9F B2 25 B6 47 44 3F D5 C4 9D 62 0E 4C 9C 00 6A E7 73 C2 E4 24 CD 91 E5 77 F0 9C 26 F0 CD EF EA BD 00
16:38:48.884 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - A4 C6 02 1B 53 20 B5 12 41 A5 DC 5B 05 1A EA 40 72 1A A0 A3 E3 22 A1 25 78 D9 69 D6 24 C1 36 06 CD E5 89 6B 03 DE F2 F9 56 95 B2 EF A8 DD 22 76 96 84 FE 50 DA 8D 5E 71 98 8E 09 FC 16 2E B7 17 18 2B B5 55 E6 E2 99 C2 00 00
16:38:49.206 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 00 B1 8B AC 35 AA 6B 7A 2D 9B 28 FF D4 FA A5 B9 DA CF CC 3F A3 00 00 80 00 00 00 00 00 00 00
16:38:49.209 [nioEventLoopGroup-2-1] INFO wowchat.realm.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Mistblade
16:38:49.219 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0010 - 00 00 00 00
16:38:49.533 [nioEventLoopGroup-2-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0010 - 00 00 00 00 03 00 00 01 02 4D 69 73 74 62 6C 61 64 65 20 50 54 52 00 31 34 31 2E 39 35 2E 31 35 37 2E 31 33 36 3A 38 30 38 39 00 0A D7 23 3C 00 01 02 01 00 00 4D 69 73 74 62 6C 61 64 65 00 31 34 31 2E 39 35 2E 31 35 37 2E 31 33 36 3A 38 30 38 35 00 00 00 00 00 02 01 02 01 00 02 54 65 72 65 6E 61 73 20 5B 57 6F 74 4C 4B 20 50 54 52 5D 00 31 30 39 2E 32 33 36 2E 38 36 2E 39 32 3A 38 30 38 35 00 00 00 00 00 00 01 02 10 00
16:38:49.583 [nioEventLoopGroup-2-1] INFO wowchat.game.GameConnector - Connecting to game server Mistblade (141.95.157.136:8085)
16:38:50.033 [nioEventLoopGroup-2-2] INFO wowchat.game.GamePacketHandlerMoP18414 - Connected! Authenticating...
16:38:50.348 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketDecoderMoP - RECV PACKET: 4F57 - 52 4C 44 20 4F 46 20 57 41 52 43 52 41 46 54 20 43 4F 4E 4E 45 43 54 49 4F 4E 20 2D 20 53 45 52 56 45 52 20 54 4F 20 43 4C 49 45 4E 54
16:38:50.398 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketEncoderMoP - SEND PACKET: 4F57 - 52 4C 44 20 4F 46 20 57 41 52 43 52 41 46 54 20 43 4F 4E 4E 45 43 54 49 4F 4E 20 2D 20 43 4C 49 45 4E 54 20 54 4F 20 53 45 52 56 45 52 00
16:38:50.828 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketDecoderMoP - RECV PACKET: 0949 - 00 00 09 EF 1C B8 F4 84 FA A2 F8 55 81 37 37 31 DB AC 61 3B 4B C7 E2 F8 5B 2F D1 FA C2 2A 84 F3 C6 A0 01 64 DB 02 E4
16:38:50.988 [nioEventLoopGroup-2-2] DEBUG wowchat.game.GamePacketEncoderMoP - SEND PACKET: 00B2 - 00 00 00 00 00 00 00 00 00 00 8E 9D 74 A7 C6 01 00 00 00 4D 12 9C 38 ED CD 01 00 F3 13 39 00 00 00 00 00 00 00 00 00 00 00 00 B2 64 2B 66 EE 47 49 A4 C1 80 3D C6 72 01 00 00 30 05 00 00 78 9C 75 93 61 6E 83 30 0C 85 D9 3D 76 84 5D A2 ED 56 D4 A9 48 AC D0 FE 9D 4C E2 82 45 88 91 09 6C ED E5 B7 A0 49 D3 26 39 FC E4 7B 76 E2 97 E7 A7 2C CB B6 8E EE 77 10 FB BE 31 1D E1 82 03 FA 70 3E 64 0F C3 C7 E3 31 FB C7 C5 74 80 EC B8 BD 25 38 7A D0 C9 6C 02 B1 57 D9 16 A4 41 99 3A 1E 13 38 04 87 57 42 67 0B F2 34 C0 A8 89 C8 5B F2 AD DE C0 81 E9 0B 90 1E F5 A9 76 E0 D0 5B 10 0D 75 E0 22 6C 71 D2 2B 1D 45 AB 2A 58 D0 5E 40 08 1A 87 93 26 E3 A1 81 70 E4 36 C9 6A FC 0C 3A 1C C1 84 13 90 DD 0B 0C 7A F3 F3 BE 14 BE 92 7E F4 33 36 73 5B 33 3B 0D BE 78 C3 B3 0F 28 AF 3C 8B 07 A7 48 72 77 1B 3B 75 F6 BC 88 E6 E8 86 E6 45 35 CB 82 7A 46 F2 99 9C DD 82 EF D3 74 C7 3E 08 BB B4 40 25 07 3F 8D 68 F4 1B 1D 02 0E 1B 17 27 85 64 0A 57 49 C5 26 86 24 95 A3 55 71 1E 5B 01 8B 2A 3F 32 F7 B1 76 CF 92 BE 64 01 46 58 27 BC 60 09 56 21 25 86 9F 1D 50 EB 22 4D 3F DF 9A 1C B5 EA 84 57 96 36 35 69 BD 6E 84 EE 64 4D 03 16 E0 A1 45 6D 5F 6A EE 51 B7 B7 5E 6D AB 7A 72 FA B3 46 4C 1E 45 65 17 26 5B 05 96 78 A6 EE C0 A5 54 FF BF CD 38 85 5D C7 64 50 A1 6B 47 BD DF 66 0E DD EF E2 FF 55 7C C5 EF 1B 7A EB 96 C4 00 90 50 41 4E 44 49 43 48 41 54
16:39:11.706 [JDA RateLimit-Worker 3] DEBUG net.dv8tion.jda.internal.requests.RateLimiter - Removed 2 expired buckets
16:39:51.004 [nioEventLoopGroup-2-2] ERROR wowchat.common.IdleStateCallback - Network state for reader marked as idle!
16:39:51.020 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 15 thread-local buffer(s) from thread: nioEventLoopGroup-2-1
16:39:51.021 [nioEventLoopGroup-2-2] DEBUG wowchat.common.ReconnectDelay - GET RECONNECT DELAY 10
16:39:51.021 [nioEventLoopGroup-2-2] INFO wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...
16:39:51.199 [JDA Gateway-Worker 1] DEBUG net.dv8tion.jda.internal.requests.WebSocketClient - Sending normal message {"op":3,"d":{"activities":[{"name":"Connecting...","type":0}],"afk":false,"since":1650487191020,"status":"online"}}
16:39:53.118 [nioEventLoopGroup-2-2] DEBUG io.netty.buffer.PoolThreadCache - Freed 9 thread-local buffer(s) from thread: nioEventLoopGroup-2-2
16:40:01.035 [pool-1-thread-1] INFO wowchat.realm.RealmConnector - Connecting to realm server logon.stormforge.gg:3724
16:40:01.366 [nioEventLoopGroup-3-1] INFO wowchat.realm.RealmPacketHandlerTBC - Connected! Sending account login information...
16:40:01.371 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0000 - 08 27 00 57 6F 57 00 05 04 08 EE 47 36 38 78 00 58 53 4F 00 53 55 6E 65 00 00 00 00 7F 00 00 01 09 50 41 4E 44 49 43 48 41 54
16:40:01.689 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0000 - 00 00 6D 1A 9A B2 0A 0D AC A6 F3 CA 91 CA 10 F0 24 35 9D 82 82 5E 07 9F AA FA AA 31 8F B7 D7 C9 E9 79 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 E1 89 5E 64 4B 89 67 A9 2C 77 D2 0C 9B 13 50 69 45 46 C5 81 EE 56 E5 29 AB C1 07 12 90 1D 58 42 8D 36 69 44 87 CD A5 65 88 45 53 CA D0 27 FF 18 1D B1 1A 5E 97 8F 00
16:40:01.732 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0001 - 32 C6 E1 C7 0C CA 4E 55 13 EA 44 F9 DE 21 A5 79 DC AC 20 66 F9 2B 4E CC 89 1B 45 09 87 3E 8A 62 F2 ED DA 4D 50 FB DF 36 42 96 63 EA 2E 7B F2 36 6A 1C E9 FD CC C5 0F 0F FD 6E 84 B0 1C 1C 7E B8 9D ED 75 17 C7 3D 5E 76 00 00
16:40:01.986 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0001 - 00 DF 64 EB F3 CB 91 68 F8 D8 DB 0E A8 79 8E BC 6F E6 7A 51 75 00 00 80 00 00 00 00 00 00 00
16:40:01.990 [nioEventLoopGroup-3-1] INFO wowchat.realm.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Mistblade
16:40:01.991 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketEncoder - SEND REALM PACKET: 0010 - 00 00 00 00
16:40:02.304 [nioEventLoopGroup-3-1] DEBUG wowchat.realm.RealmPacketDecoder - RECV REALM PACKET: 0010 - 00 00 00 00 03 00 00 01 02 4D 69 73 74 62 6C 61 64 65 20 50 54 52 00 31 34 31 2E 39 35 2E 31 35 37 2E 31 33 36 3A 38 30 38 39 00 0A D7 23 3C 00 01 02 01 00 00 4D 69 73 74 62 6C 61 64 65 00 31 34 31 2E 39 35 2E 31 35 37 2E 31 33 36 3A 38 30 38 35 00 00 00 00 00 02 01 02 01 00 02 54 65 72 65 6E 61 73 20 5B 57 6F 74 4C 4B 20 50 54 52 5D 00 31 30 39 2E 32 33 36 2E 38 36 2E 39 32 3A 38 30 38 35 00 00 00 00 00 00 01 02 10 00
16:40:02.309 [nioEventLoopGroup-3-1] INFO wowchat.game.GameConnector - Connecting to game server Mistblade (141.95.157.136:8085)
16:40:02.594 [nioEventLoopGroup-3-2] INFO wowchat.game.GamePacketHandlerMoP18414 - Connected! Authenticating...
16:40:02.852 [nioEventLoopGroup-3-2] DEBUG wowchat.game.GamePacketDecoderMoP - RECV PACKET: 4F57 - 52 4C 44 20 4F 46 20 57 41 52 43 52 41 46 54 20 43 4F 4E 4E 45 43 54 49 4F 4E 20 2D 20 53 45 52 56 45 52 20 54 4F 20 43 4C 49 45 4E 54
16:40:02.859 [nioEventLoopGroup-3-2] DEBUG wowchat.game.GamePacketEncoderMoP - SEND PACKET: 4F57 - 52 4C 44 20 4F 46 20 57 41 52 43 52 41 46 54 20 43 4F 4E 4E 45 43 54 49 4F 4E 20 2D 20 43 4C 49 45 4E 54 20 54 4F 20 53 45 52 56 45 52 00
16:40:03.215 [nioEventLoopGroup-3-2] DEBUG wowchat.game.GamePacketDecoderMoP - RECV PACKET: 0949 - 00 00 6D 2F 78 1F 80 7F A7 57 A4 43 3D 47 A5 5B 6F F8 09 A4 52 B7 F2 51 05 1E AC 05 7D 60 50 D9 67 9D 01 EB F2 8E FB
16:40:03.316 [nioEventLoopGroup-3-2] DEBUG wowchat.game.GamePacketEncoderMoP - SEND PACKET: 00B2 - 00 00 00 00 00 00 00 00 00 00 88 A9 96 EC 65 01 00 00 00 E3 E9 C6 95 10 05 01 00 94 53 71 00 00 00 00 00 00 00 00 00 00 00 00 42 D0 01 4B EE 47 6A 0F 98 24 04 23 72 01 00 00 30 05 00 00 78 9C 75 93 61 6E 83 30 0C 85 D9 3D 76 84 5D A2 ED 56 D4 A9 48 AC D0 FE 9D 4C E2 82 45 88 91 09 6C ED E5 B7 A0 49 D3 26 39 FC E4 7B 76 E2 97 E7 A7 2C CB B6 8E EE 77 10 FB BE 31 1D E1 82 03 FA 70 3E 64 0F C3 C7 E3 31 FB C7 C5 74 80 EC B8 BD 25 38 7A D0 C9 6C 02 B1 57 D9 16 A4 41 99 3A 1E 13 38 04 87 57 42 67 0B F2 34 C0 A8 89 C8 5B F2 AD DE C0 81 E9 0B 90 1E F5 A9 76 E0 D0 5B 10 0D 75 E0 22 6C 71 D2 2B 1D 45 AB 2A 58 D0 5E 40 08 1A 87 93 26 E3 A1 81 70 E4 36 C9 6A FC 0C 3A 1C C1 84 13 90 DD 0B 0C 7A F3 F3 BE 14 BE 92 7E F4 33 36 73 5B 33 3B 0D BE 78 C3 B3 0F 28 AF 3C 8B 07 A7 48 72 77 1B 3B 75 F6 BC 88 E6 E8 86 E6 45 35 CB 82 7A 46 F2 99 9C DD 82 EF D3 74 C7 3E 08 BB B4 40 25 07 3F 8D 68 F4 1B 1D 02 0E 1B 17 27 85 64 0A 57 49 C5 26 86 24 95 A3 55 71 1E 5B 01 8B 2A 3F 32 F7 B1 76 CF 92 BE 64 01 46 58 27 BC 60 09 56 21 25 86 9F 1D 50 EB 22 4D 3F DF 9A 1C B5 EA 84 57 96 36 35 69 BD 6E 84 EE 64 4D 03 16 E0 A1 45 6D 5F 6A EE 51 B7 B7 5E 6D AB 7A 72 FA B3 46 4C 1E 45 65 17 26 5B 05 96 78 A6 EE C0 A5 54 FF BF CD 38 85 5D C7 64 50 A1 6B 47 BD DF 66 0E DD EF E2 FF 55 7C C5 EF 1B 7A EB 96 C4 00 90 50 41 4E 44 49 43 48 41 54
```

**Comment by fjaros** [comment] 2022-04-21 17:48
Hey there,
yeah I received several reports from this server not working last night. So don't worry, it's not just you. I have no idea what they changed nor have I ever heard of this server. The original implementation for MoP was for Tauri evermoon realm I believe some 4 years ago. I am currently on vacation but will be back home next week and I can try seeing what's going on. Until then you're out of luck. Best bet would be to alert the developers of the server and ask what changed in the login sequence for the game server which is where the bot is getting stuck - basically it sends your account name and password to the server for authentication but never hears back from the server.

**Comment by Vishiswaz** [comment] 2022-04-22 02:43
For the record, Stormforge is a merge between Tauri and this other pserver group called Atlantiss. Mistblade, the MoP server they're running, is mostly on Tauri code, the same as Evermoon, with very slight branched changes done by both the Atlantiss devs and the Tauri devs themselves.

If they did something that borked it on Mistblade, it'll probably break on Evermoon as well once Evermoon gets its next restart/update, which isn't very often. They're allegedly running off the same code.

**Comment by fjaros** [comment] 2022-04-22 03:22
Another user got in touch with Mistblade devs and they figured out the issue. Fix will be released soon.

**Comment by Vishiswaz** [comment] 2022-04-22 03:24
Excellent. Thanks!

Oh and on a mostly unrelated topic, the admins at Apollo have now decided the bot is against their rules now. In case anyone comes looking here asking why the bot doesn't work there.

Stupid decision, but that's Apollo for you.

**Comment by fjaros** [comment] 2022-04-22 03:30
@Vishiswaz as in they broke something that makes it not connect? Or are they just banning the accounts if they find out it's a bot?
If they somehow manipulated the connection, that could probably be fixed. For the bans I guess just keep making new accounts lol

**Comment by Vishiswaz** [comment] 2022-04-22 03:32
I'm not entirely sure, I was informed by my guildies who play there that the GMs told them the bot was no bueno anymore. I don't think there's any getting around it, ban or otherwise, since we were warned, and the chat bot is pretty easy to spot.

**Comment by fjaros** [comment] 2022-04-22 04:11
Fixed via https://github.com/fjaros/wowchat/commit/b19a9497706880ffee8c1da391750193ba641b4c . Please redownload the release zip file. I did not create a new release for this fix.

**Closed by fjaros** 2022-04-22 04:11 UTC

**Comment by Vishiswaz** [comment] 2022-04-22 04:15
Confirmed working
