### ISSUE TITLE
Any solutions on Warden on windows is not support and mac is TBC?

### ISSUE THREAD

**Issue by wang735249037** [fjaros/wowchat#84] opened 2022-09-01 11:33 UTC
HI, I am using this great work to connect to Warmane.
But When I set the platform=Windows, it can log in game (I can got messages on Discord.) but lost connection in a few seconds.(ERROR w.g.GamePacketHandlerWotLK -WARDEN on Windows is not supproted, Bot will soon disconnect. try to use platform mac.)
and when I set it to Mac (others keep unchanged), it says (Error w.r.RealmPacketHandleTBC Invalid game version for this server)
since I tried on both windows and mac, and got the same issue. does it mean I can not use it on this server?
Ty in advance

**Comment by fjaros** [comment] 2022-09-01 16:23
Duplicate of https://github.com/fjaros/wowchat/issues/75

TL;DR - No, there is no way to make Windows warden work. For warmane, seems Mac login does work when your account is not newly created. Try waiting a few days.

**Closed** 2022-09-01 16:23 UTC
Labels: duplicate
