### ISSUE TITLE
Bot not reading ingame messages

### ISSUE THREAD

**Issue by disclosurez** [fjaros/wowchat#22] opened 2019-05-10 10:50 UTC
The bot is not reading ingame messages, but is sending messages from the discord channel to the ingame channel, this worked before today.

**Comment by fjaros** [comment] 2019-05-10 18:19
This gives me no information to help you. Please include the following:
- Which server/expansion are you playing on?
- Are there any exceptions in the console/log when you run the bot?
- Does it work on another character?
- You can also set GamePacketDecoder and GamePacketEncoder settings to log DEBUG messages to dump raw network traffic to the log. Then we can see if the bot is receiving the messages from the game or not.

You can see here an example of a good bug report: https://github.com/fjaros/wowchat/issues/14

**Comment by disclosurez** [comment] 2019-05-10 19:39
> 
> 
> This gives me no information to help you. Please include the following:
> 
>     * Which server/expansion are you playing on?
> 
>     * Are there any exceptions in the console/log when you run the bot?
> 
>     * Does it work on another character?
> 
>     * You can also set GamePacketDecoder and GamePacketEncoder settings to log DEBUG messages to dump raw network traffic to the log. Then we can see if the bot is receiving the messages from the game or not.
> 
> 
> You can see here an example of a good bug report: #14

3.3.5
No exceptions
No

21:38:23.133 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.1
21:38:26.113 INFO  wowchat.WoWChat$ - Connecting to Discord...
21:38:26.896 INFO  n.d.jda.core.JDA - Login Successful!
21:38:27.242 INFO  n.d.j.c.r.WebSocketClient - Connected to WebSocket
21:38:27.576 INFO  n.d.jda.core.JDA - Finished Loading!
21:38:27.654 INFO  w.r.RealmConnector - Connecting to realm server logon.dreamworkz.net:3724
21:38:27.785 INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
21:38:27.834 INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Dreamworkz
21:38:27.849 INFO  w.g.GameConnector - Connecting to game server Dreamworkz (51.89.139.182:8085)
21:38:27.890 INFO  w.g.GamePacketHandlerWotLK - Connected! Authenticating...
21:38:27.921 INFO  w.g.GamePacketHandlerWotLK - Successfully logged in!
21:38:27.947 INFO  w.g.GamePacketHandlerWotLK - Logging in with character Discord
21:38:27.961 INFO  w.g.GamePacketHandlerWotLK - Successfully joined the world!
21:38:27.966 INFO  w.g.GamePacketHandlerWotLK - Joining channel world
21:38:27.966 INFO  w.g.GamePacketHandlerWotLK - Joining channel Trade - City
21:38:27.967 INFO  w.g.GamePacketHandlerWotLK - Joining channel Cast
21:38:27.968 INFO  w.g.GamePacketHandlerWotLK - Joining channel warriors
21:38:27.996 INFO  w.g.GamePacketHandlerWotLK - Notification: GM mode is ON

**Comment by disclosurez** [comment] 2019-05-10 21:09
23:08:30.295 DEBUG w.g.GamePacketEncoder - SEND PACKET: 01DC - 00 00 00 00 66 00 00 00
23:09:00.273 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...

**Comment by fjaros** [comment] 2019-05-10 22:20
Do you see RECV PACKET: 0096 ? These are chat messages. If so please paste example of those ones. I can check it out on the server tonight.

**Comment by fjaros** [comment] 2019-05-11 02:29
I checked out the dreamworkz server. The server must have changed something in the core code because the bot doesn't receive any chat messages and gets kicked off after 2 minutes automatically. i am not sure what the bot is doing differently vs a real client. please feel free to get me in touch with the server dev so we can work on a fix.

**Comment by disclosurez** [comment] 2019-05-11 10:09
I am the dev of that server, nothing has changed

**Comment by fjaros** [comment] 2019-05-12 00:23
The root cause was the packet parser broke when extra long ( > 0x7FFF in length) packets were received by the bot. These packets use an extra byte for the header vs regular packets to express the long size. I thought that this behavior was only implemented in cataclysm but seems that WotLK also supports it. Fixed in https://github.com/fjaros/wowchat/commit/d8901c85b9e9464338096f58990107da6b1aedf9

**Closed by fjaros** 2019-05-12 00:23 UTC
