### ISSUE TITLE
Adding functionality for command like behavior 

### ISSUE THREAD

**Issue by fluffyst** [fjaros/wowchat#38] opened 2020-10-02 19:13 UTC
Probably a shit title, but I'm trying to figure out how I can send a /invite {name} when someone types say "ghetto" in either chat or discord chat (if their name matches)

I thought about looking at how dot commands work, because I assume it would be similar but I can't get that to output any response either, perhaps some guidance would be greatly appreciated!

**Comment by fjaros** [comment] 2020-10-02 19:21
Duplicate of https://github.com/fjaros/wowchat/issues/29 . You can read the longer explanation in this issue. It's not so straight forward - you would have to implement the concrete packet for each of your wanted commands.

**Closed** 2020-10-03 00:06 UTC
Labels: duplicate

**Comment by fluffyst** [comment] 2020-10-03 01:42
Hey, thanks for the info! So i'm trying to implement this locally just to test it out, I figured out the packet I need to send with [wowscout](https://github.com/tripleslash/wowscout), and I can send it fine with the wowscout tool, but not within the bot.

I do get the log info so I 100% know it's hitting the method, but it doesn't seem to work and I have no debug info as to why.

```
    protected def sendGroupInvite(target: String): Unit = {
    val out = PooledByteBufAllocator.DEFAULT.buffer(64, 64)
      
    val utf8TargetBytes = target.getBytes("UTF-8")
    out.writeBytes(utf8TargetBytes)

    ctx.get.writeAndFlush(Packet(CMSG_GROUP_INVITE, out))

    logger.info(s"target | bytes: ${target} -- ${target.getBytes("UTF-8")} -- ${ByteUtils.toHexString(utf8TargetBytes)}")
    // logger.info(s"out | packet: ${out} ${packet}")
  }
```
and
```
protected def sendGroupInvite(target: String): Unit = {
    ctx.foreach(ctx => {
    val out = PooledByteBufAllocator.DEFAULT.buffer(64, 64)
    out.writeBytes(target.getBytes("UTF-8"))
      val packet = Packet(CMSG_GROUP_INVITE, out)
      ctx.writeAndFlush(packet)

      logger.info(s"target | bytes: ${target} -- ${target.getBytes("UTF-8")}")
    })
  }
```

Is what I've tried so far.

I'm not 100% sure but I think ctx.writeAndFlush is what adds a packet to the queue and sends it? 

Sorry to bother!

**Comment by fjaros** [comment] 2020-10-03 02:10
Yeah couple of things - 1) you should be sending CMSG_GUILD_INVITE (not group, group means party). The opcode is 0x82.
2) Strings sent between client and server are null terminated for pre-cata wow in lieu of sending a string length marker before sending the actually string. this means you need to write byte 0 after you insert the string.

**Comment by fluffyst** [comment] 2020-10-03 02:24
I want to send **party** invites, for "ghetto" hearths, which I'm using 0x6E for.
```
val utf8TargetBytes = target.getBytes("UTF-8")
out.writeBytes(utf8TargetBytes)
out.writeByte(0)
```
I assume is what you mean, doesn't seem to make a difference, the only thing I can think that is wrong is i've set the buffer size to 64, 64, i'm not exactly sure how to find out what the size should be if names can be dynamic.

**Comment by fjaros** [comment] 2020-10-03 03:11
Buffer set to 64, 64 is totally fine. This should work then if we consider the server side code -> https://github.com/cmangos/mangos-tbc/blob/master/src/game/Groups/GroupHandler.cpp#L53

Turn on the debug logging for raw packets (in GamePacketEncoder & GamePacketDecoder. Do you receive error back?

**Comment by fluffyst** [comment] 2020-10-05 21:18
Turns out the server I was playing on didn't allow level 1 characters to send group invites x) Thanks for the help!
