### ISSUE TITLE
Suggestion regarding to moderation

### ISSUE THREAD

**Issue by MrTide** [fjaros/wowchat#100] opened 2023-05-03 19:19 UTC
Hello once again, i am not sure this is the right place to ask but
I can't believe how awesome wowchat is i am falling in love with it
I wonder if you can add ingame moderation function to it as well, read a word and apply a command like gm commands or discord/gkick command and so on.
Thank you in for taking the time and creating this master piece!
It would be really nice if you consider.
I have it on weakaura atm but it would be really nice

**Comment by fjaros** [comment] 2023-05-04 00:10
Duplicate of #29 . The reasons listed in that issue are still relevant.

**Comment by MrTide** [comment] 2023-05-04 10:03
> Duplicate of #29 . The reasons listed in that issue are still relevant.

Thank you for taking a look, my suggestion was that maybe this bot could read a channel or say/yell chat ingame and apply a command to that player more like trigger (player X said the N-Word .kick playername or /kick from the channel) i dont want it to send anything to the server, thanks for taking a look <3

**Comment by fjaros** [comment] 2023-05-04 15:50
Ah I see, you're talking about Discord moderation from in-game. Either way, the access control would still have to be designed and implemented. You wouldn't want everyone who can talk to the bot having access to kick people from Discord. It's not a bad idea, but as this project is on maintenance mode, I don't plan on implementing such a large feature. And also, the workaround of just going to your Discord client and kicking that person out is quite sufficient.

**Comment by fjaros** [comment] 2023-05-04 18:03
I see so in the end you do want wow in-game chat moderation... Sorry it is very unclear from your messages what you actually mean in the context of the functionality of the bot.
This unfortunately will require some coding modifications. In the simplest form:
1. You will have to setup a relay from that channel -> discord
2. You can get inspired by implementation of filters - https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/discord/Discord.scala#L73
3. You will have to implement a function like shouldFilter, let's call it "shouldModerate". Inside this function, you should decide what action to take based on the content of the message, channel it is sent in, and who sent it.
4. If you decide an action is needed, you can then use the Global.game.foreach(_.sendMessageToWow(<arguments>)) construct to send the moderation command back to the game server. You can see this function being used to notify users of errors (such as for a failed @ tag notification).

Happy coding 😄

**Closed** 2023-05-06 21:43 UTC
Labels: duplicate, enhancement
